# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quit_dialog_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class quit_dialog(object):
    def setupUi(self, quit_dialog):
        quit_dialog.setObjectName("quit_dialog")
        quit_dialog.resize(400, 150)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/quit.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        quit_dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(quit_dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(quit_dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(quit_dialog)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            63, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_yes = QtWidgets.QPushButton(self.frame_2)
        self.btn_yes.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_yes.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_yes.setFont(font)
        self.btn_yes.setObjectName("btn_yes")
        self.horizontalLayout.addWidget(self.btn_yes)
        self.btn_save = QtWidgets.QPushButton(self.frame_2)
        self.btn_save.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_save.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.btn_no = QtWidgets.QPushButton(self.frame_2)
        self.btn_no.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_no.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_no.setFont(font)
        self.btn_no.setObjectName("btn_no")
        self.horizontalLayout.addWidget(self.btn_no)
        spacerItem1 = QtWidgets.QSpacerItem(
            62, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(quit_dialog)
        QtCore.QMetaObject.connectSlotsByName(quit_dialog)

    def retranslateUi(self, quit_dialog):
        _translate = QtCore.QCoreApplication.translate
        quit_dialog.setWindowTitle(_translate("quit_dialog", "Dialog"))
        self.label.setText(_translate(
            "quit_dialog", "Work is un-saved. Are you sure you want to quit?"))
        self.btn_yes.setText(_translate("quit_dialog", "Yes"))
        self.btn_save.setText(_translate("quit_dialog", "Save"))
        self.btn_no.setText(_translate("quit_dialog", "No"))
